### PR TITLE
Add an Instruction Inspector plugin.

### PR DESCRIPTION
**Pull request by 10110111**
The new plugin displays Capstone-supplied info about the selected instruction.

It also allows to compare output of multiple disassemblers with Capstone's output. The disassemblers for comparison are (when installed in the system): `ndisasm`, `objdump` and Agner Fog's `objconv`.

### CODE REVIEW

**Comment by eteran** [comment]
Hmm, it looks like `x86_xop_cc` isn't in the version of capstone that our test scripts use.

**Comment by 10110111** [comment]
Ah, right... Will look for a fix.

**Comment by eteran** [comment]
Yea, looks like 4.0-alpha1 was the first version to that that `enum` Perhaps we can just check `CS_API_MAJOR ` and `CS_API_MINOR ` and conditionally support printing instructions of that type?

**Comment by 10110111** [comment]
Yeah, it seems we already do this in `Instruction`.

**Comment by 10110111** [comment]
Should now work.

**Comment by eteran** [comment]
I plan to merge once 0.9.21 is tagged and we get the grsecurity/gentoo ebuild stuff sorted. Thanks!

**Pull request merged**
