### PR TITLE
Add support for gdtoa-desktop and libdouble-conversion to format floating-point values better

### PR DESCRIPTION
**Pull request by 10110111**

### CODE REVIEW

**Comment by eteran** [comment]
This builds on Travis, but I get errors on my local machine:

```
$  cmake ..
-- The CXX compiler identification is GNU 7.3.0
-- Check for working CXX compiler: /usr/x86_64-pc-linux-gnu/gcc-bin/7.3.0/c++
-- Check for working CXX compiler: /usr/x86_64-pc-linux-gnu/gcc-bin/7.3.0/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Boost version: 1.65.0
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
-- Checking for module 'capstone>=3.0.4'
--   Found capstone, version 3.0.5
-- Checking for module 'libgvc>=2.38.0'
--   Found libgvc, version 2.40.1
-- Checking for module 'double-conversion'
--   Found double-conversion, version 2.0.1
-- Checking for module 'gdtoa-desktop'
--   No package 'gdtoa-desktop' found
CMake Warning at CMakeLists.txt:105 (message):
  gdtoa-desktop package wasn't found.  80-bit floating-point values will be
  showed with max_digits10 digits of precision instead of shortest
  representation.


-- Configuring done
CMake Error at src/CMakeLists.txt:231 (add_executable):
  Target "edb" links to target "double-conversion::double-conversion" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?


CMake Error at plugins/DebuggerCore/CMakeLists.txt:126 (add_library):
  Target "DebuggerCore" links to target
  "double-conversion::double-conversion" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?


CMake Error at plugins/Analyzer/CMakeLists.txt:13 (add_library):
  Target "Analyzer" links to target "double-conversion::double-conversion"
  but the target was not found.  Perhaps a find_package() call is missing for
  an IMPORTED target, or an ALIAS target is missing?


CMake Error at plugins/Assembler/CMakeLists.txt:13 (add_library):
  Target "Assembler" links to target "double-conversion::double-conversion"
  but the target was not found.  Perhaps a find_package() call is missing for
  an IMPORTED target, or an ALIAS target is missing?


CMake Error at plugins/BinaryInfo/CMakeLists.txt:13 (add_library):
  Target "BinaryInfo" links to target "double-conversion::double-conversion"
  but the target was not found.  Perhaps a find_package() call is missing for
  an IMPORTED target, or an ALIAS target is missing?


CMake Error at plugins/Bookmarks/CMakeLists.txt:13 (add_library):
  Target "Bookmarks" links to target "double-conversion::double-conversion"
  but the target was not found.  Perhaps a find_package() call is missing for
  an IMPORTED target, or an ALIAS target is missing?


CMake Error at plugins/BreakpointManager/CMakeLists.txt:13 (add_library):
  Target "BreakpointManager" links to target
  "double-conversion::double-conversion" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?


CMake Error at plugins/CheckVersion/CMakeLists.txt:13 (add_library):
  Target "CheckVersion" links to target
  "double-conversion::double-conversion" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?


CMake Error at plugins/OpcodeSearcher/CMakeLists.txt:13 (add_library):
  Target "OpcodeSearcher" links to target
  "double-conversion::double-conversion" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?


CMake Error at plugins/ProcessProperties/CMakeLists.txt:13 (add_library):
  Target "ProcessProperties" links to target
  "double-conversion::double-conversion" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?


CMake Error at plugins/ROPTool/CMakeLists.txt:13 (add_library):
  Target "ROPTool" links to target "double-conversion::double-conversion" but
  the target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?


CMake Error at plugins/References/CMakeLists.txt:13 (add_library):
  Target "References" links to target "double-conversion::double-conversion"
  but the target was not found.  Perhaps a find_package() call is missing for
  an IMPORTED target, or an ALIAS target is missing?


CMake Error at plugins/SymbolViewer/CMakeLists.txt:13 (add_library):
  Target "SymbolViewer" links to target
  "double-conversion::double-conversion" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?


CMake Error at plugins/Backtrace/CMakeLists.txt:13 (add_library):
  Target "Backtrace" links to target "double-conversion::double-conversion"
  but the target was not found.  Perhaps a find_package() call is missing for
  an IMPORTED target, or an ALIAS target is missing?


CMake Error at plugins/DumpState/CMakeLists.txt:13 (add_library):
  Target "DumpState" links to target "double-conversion::double-conversion"
  but the target was not found.  Perhaps a find_package() call is missing for
  an IMPORTED target, or an ALIAS target is missing?


CMake Error at plugins/FunctionFinder/CMakeLists.txt:13 (add_library):
  Target "FunctionFinder" links to target
  "double-conversion::double-conversion" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?


CMake Error at plugins/DebuggerErrorConsole/CMakeLists.txt:13 (add_library):
  Target "DebuggerErrorConsole" links to target
  "double-conversion::double-conversion" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?


CMake Error at plugins/BinarySearcher/CMakeLists.txt:13 (add_library):
  Target "BinarySearcher" links to target
  "double-conversion::double-conversion" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?


CMake Error at plugins/InstructionInspector/CMakeLists.txt:13 (add_library):
  Target "InstructionInspector" links to target
  "double-conversion::double-conversion" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?


CMake Error at plugins/HardwareBreakpoints/CMakeLists.txt:13 (add_library):
  Target "HardwareBreakpoints" links to target
  "double-conversion::double-conversion" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?


CMake Error at plugins/HeapAnalyzer/CMakeLists.txt:13 (add_library):
  Target "HeapAnalyzer" links to target
  "double-conversion::double-conversion" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?


CMake Error at plugins/ODbgRegisterView/CMakeLists.txt:58 (add_library):
  Target "ODbgRegisterView" links to target
  "double-conversion::double-conversion" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?


-- Generating done
-- Build files have been written to: /home/eteran/projects/edb-debugger/build
```

Any suggestions?

**Comment by eteran** [comment]
Looks like it actually generates the CMake build files, the errors are quite loud and would confuse users.

**Comment by eteran** [comment]
It also doesn't link :-/

`/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -ldouble-conversion::double-conversion`

**Comment by 10110111** [comment]
Unfortunately, the fix doesn't work on my system: I get linker errors as if `${double-conversion_LIBRARIES}` is empty. I guess I'll have to check with double-conversion 2.0 instead of my current 3.0.

**Comment by 10110111** [comment]
So, we may go two ways. First is adding compatibility `if`/`else` clause:
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index b9555a02..70beff3a 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -51,7 +51,12 @@ if(NOT double-conversion_FOUND)
     message(WARNING "libdouble-conversion development package wasn't found. 32- and 64-bit floating-point values will be showed with max_digits10 digits of precision instead of shortest representation.")
 else()
     message(STATUS "  Found double-conversion, version ${double-conversion_VERSION}")
-    set(DOUBLE_CONVERSION_LIBRARIES ${double-conversion_LIBRARIES})
+    if(NOT DEFINED double-conversion_LIBRARIES)
+        set(DOUBLE_CONVERSION_LIBRARIES double-conversion::double-conversion)
+    else()
+        # support for older version of the library
+        set(DOUBLE_CONVERSION_LIBRARIES ${double-conversion_LIBRARIES})
+    endif()
     add_definitions("-DHAVE_DOUBLE_CONVERSION")
 endif()
 
```
Another way is to drop all this `find_package` stuff and instead use the `CheckIncludeFileCXX` module and `find_library`:
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index b9555a02..f581c5be 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -19,6 +19,7 @@ endif()
 set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${PROJECT_SOURCE_DIR}/cmake/Modules/")
 
 include("GNUInstallDirs")
+include("CheckIncludeFileCXX")
 
 find_package(Boost 1.35 REQUIRED)
 include_directories(${Boost_INCLUDE_DIR})
@@ -45,14 +46,17 @@ if (UNIX)
 endif()
 
 message(STATUS "Checking for module 'double-conversion'")
-find_package(double-conversion QUIET)
-if(NOT double-conversion_FOUND)
-    UNSET(double-conversion_FOUND CACHE)
-    message(WARNING "libdouble-conversion development package wasn't found. 32- and 64-bit floating-point values will be showed with max_digits10 digits of precision instead of shortest representation.")
+check_include_file_cxx("double-conversion/double-conversion.h" HAVE_DOUBLE_CONVERSION)
+if(NOT HAVE_DOUBLE_CONVERSION)
+   UNSET(HAVE_DOUBLE_CONVERSION CACHE)
+   message(WARNING      "libdouble-conversion header wasn't found. 32- and 64-bit floating-point values will be showed with max_digits10 digits of precision instead of shortest representation.")
 else()
-    message(STATUS "  Found double-conversion, version ${double-conversion_VERSION}")
-    set(DOUBLE_CONVERSION_LIBRARIES ${double-conversion_LIBRARIES})
-    add_definitions("-DHAVE_DOUBLE_CONVERSION")
+   find_library(DOUBLE_CONVERSION_LIBRARIES double-conversion)
+   if(NOT DOUBLE_CONVERSION_LIBRARIES)
+       message(WARNING "libdouble-conversion library wasn't found. 32- and 64-bit floating-point values will be showed with max_digits10 digits of precision instead of shortest representation.")
+   else()
+       add_definitions("-DHAVE_DOUBLE_CONVERSION")
+   endif()
 endif()
 
 find_package(Qt5Core)
```

**Comment by eteran** [comment]
Whichever solution you like better. Either one sounds easy enough.

**Pull request merged**
