### PR TITLE
CMake correctness

### PR DESCRIPTION
**Pull request by bb010g**
# depend upon pkg-config libraries in CMAKE better

This solves building on platforms like Nixpkgs, which has a `/nix/store/…-gdtoa-desktop-…/lib/pkgconfig/gdtoa-desktop.pc` along the lines of:

```pkg-config
prefix=/nix/store/…-gdtoa-desktop-…
libdir=/nix/store/…-gdtoa-desktop-…/lib
includedir=/nix/store/…-gdtoa-desktop-…/include

Name: gdtoa-desktop
Description: Binary↔decimal floating-point conversion library
Version: 0.1.20180730

Libs: -L${libdir} -lgdtoa-desktop
Cflags: -I${includedir}/gdtoa-desktop
```

Currently, edb-debugger will try to compile with `-I/nix/store/…-gdtoa-desktop-…/include` and fails to find `<gdtoa-desktop.h>`, as it should be compiling with `-I/nix/store/…-gdtoa-desktop-…/include/gdtoa-desktop`. CMake already provides a robust solution for this sort of thing in IMPORTED_TARGET (since 3.6), so let's use it.

See also https://cmake.org/cmake/help/latest/module/FindPkgConfig.html for documentation on IMPORTED_TARGET, and https://people.freedesktop.org/~dbn/pkg-config-guide.html for a pkg-config example using this same `includedir` pattern that trips our naive inclusion approach up.

***

# specify DEFAULT_PLUGIN_PATH in CMake better

`CMAKE_INSTALL_FULL_LIBDIR` prepends `CMAKE_INSTALL_PREFIX` to `CMAKE_INSTALL_LIBDIR` if necessary, and doesn't touch it if not (i.e. it's an absolute path).

This fixes the default plugin path for Nixpkgs packaging.

See also https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html for documentation. These `_FULL_` variants have been present since at least CMake 3.0.

---
This change is [Reviewable](https://reviewable.io/reviews/eteran/edb-debugger/760)

### CODE REVIEW

**Comment by 10110111** [comment]
> Currently, edb-debugger will try to compile with `-I/nix/store/…-gdtoa-desktop-…/include` and fails to find `<gdtoa-desktop.h>`, as it should be compiling with `-I/nix/store/…-gdtoa-desktop-…/include/gdtoa-desktop`.

Why doesn't `GDTOA_INCLUDE_DIRS` already contain the directory from pkg-config's `Cflags`?

**Comment by bb010g** [comment]
Good question. I was wondering that too, but given that I don't know a lot about pkg-config & its history and the example used the same pattern of `includedir` differing from what's passed to `cc` on `-I`, I just left it and changed the CMake invocation here.

**Comment by bb010g** [comment]
From looking around at docs & the manual page a bit more, I'm imaging that `includedir` more represents the prefix-like "installation" directory for "all" includes, like how `libdir` is the "installation" directory for "all" shared libraries? But none of that seems to be strictly enforced.

[pkgconf](http://pkgconf.org/) in its manual page talks about environment variables `PKG_CONFIG_LIBDIR` as the "[l]ist of primary directories where `.pc` files are looked up" and `PKG_CONFIG_SYSTEM_INCLUDE_PATH` as a "[l]ist of paths that are considered system include paths by the toolchain" ("a pkgconf-specific extension"), but those are still in a fork, and they're descriptions of environment variables. But they seem to support that installation/program-specific separation.

To close out, here's pkgconf's [`libpkgconf.pc.in`](https://github.com/pkgconf/pkgconf/blob/master/libpkgconf.pc.in) (an Autotools template), also following that installation/program-specific split:
```pkg-config
prefix=@prefix@
exec_prefix=${prefix}
includedir=@includedir@
libdir=@libdir@

Name: libpkgconf
Description: a library for accessing and manipulating development framework configuration
URL: http://github.com/pkgconf/pkgconf
Version: @PACKAGE_VERSION@
CFlags: -I${includedir}/pkgconf
Libs: -L${libdir} -lpkgconf
```

**Comment by eteran** [comment]
@10110111 since this effects libraries that you added support for, lemme know what you think of this change.

**Comment by 10110111** [comment]
Well, I still don't know the answer to https://github.com/eteran/edb-debugger/pull/760#issuecomment-622538733, but at least the changes do make the CMakeLists cleaner, so this PR looks good to me.

**Comment by 10110111** [comment]
Oh, actually I spoke too early. @bb010g 's branch doesn't link well to `gdtoa-desktop` for me on one of the machines.

**Comment by 10110111** [comment]
Now checked a bit further. The error I get is `/usr/bin/ld: cannot find -lgdtoa-desktop`. A revert to `HEAD^^` makes the build succeed, so it's definitely not a problem with system configuration.

I think @bb010g can reproduce this by removing the system `gdtoa-desktop` package, then installing it, as I always do on *ubuntu, into `~/opt/gdtoa-desktop`, and setting `PKG_CONFIG_PATH` appropriately.

Apparently, `link_directories`, removed by the first patch, is actually required. I guess the same would happen with `libgvc` installed into an unusual location (I simply don't have it at all, so can't say).

**Comment by bb010g** [comment]
@10110111 Could you paste your CMake invocation & resultant `gdtoa-desktop.pc` from the `~/opt/gdtoa-desktop` install here?

The [Nixpkgs-based derivation](https://github.com/bb010g/nur-packages/tree/937fcd01f3700d6dd6fd55d7c14027d925342af2/pkgs/development/libraries/gdtoa-desktop/default.nix) I'm building uses 10110111/gdtoa-desktop@c178e2c44d3644440f3502d0934ffce53bcab9b5 with a CMake invocation of:

```sh
mkdir -p build
cd build
cmake .. \
  -DCMAKE_FIND_USE_SYSTEM_PACKAGE_REGISTRY=OFF
  -DCMAKE_FIND_USE_PACKAGE_REGISTRY=OFF
  -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON
  -DCMAKE_BUILD_TYPE=Release
  -DCMAKE_SKIP_BUILD_RPATH=ON
  -DBUILD_TESTING=OFF
  -DCMAKE_INSTALL_LOCALEDIR=/nix/store/10xp2rc351ymxly48isbn1vv5ihhikx3-gdtoa-desktop-unstable-2020-05-01/share/locale
  -DCMAKE_INSTALL_LIBEXECDIR=/nix/store/10xp2rc351ymxly48isbn1vv5ihhikx3-gdtoa-desktop-unstable-2020-05-01/libexec
  -DCMAKE_INSTALL_LIBDIR=/nix/store/10xp2rc351ymxly48isbn1vv5ihhikx3-gdtoa-desktop-unstable-2020-05-01/lib
  -DCMAKE_INSTALL_DOCDIR=/nix/store/10xp2rc351ymxly48isbn1vv5ihhikx3-gdtoa-desktop-unstable-2020-05-01/share/doc/
  -DCMAKE_INSTALL_INFODIR=/nix/store/10xp2rc351ymxly48isbn1vv5ihhikx3-gdtoa-desktop-unstable-2020-05-01/share/info
  -DCMAKE_INSTALL_MANDIR=/nix/store/10xp2rc351ymxly48isbn1vv5ihhikx3-gdtoa-desktop-unstable-2020-05-01/share/man
  -DCMAKE_INSTALL_OLDINCLUDEDIR=/nix/store/10xp2rc351ymxly48isbn1vv5ihhikx3-gdtoa-desktop-unstable-2020-05-01/include
  -DCMAKE_INSTALL_INCLUDEDIR=/nix/store/10xp2rc351ymxly48isbn1vv5ihhikx3-gdtoa-desktop-unstable-2020-05-01/include
  -DCMAKE_INSTALL_SBINDIR=/nix/store/10xp2rc351ymxly48isbn1vv5ihhikx3-gdtoa-desktop-unstable-2020-05-01/sbin
  -DCMAKE_INSTALL_BINDIR=/nix/store/10xp2rc351ymxly48isbn1vv5ihhikx3-gdtoa-desktop-unstable-2020-05-01/bin
  -DCMAKE_INSTALL_NAME_DIR=/nix/store/10xp2rc351ymxly48isbn1vv5ihhikx3-gdtoa-desktop-unstable-2020-05-01/lib
  -DCMAKE_POLICY_DEFAULT_CMP0025=NEW
  -DCMAKE_OSX_SYSROOT=
  -DCMAKE_OSX_ARCHITECTURES=x86_64
  -DCMAKE_FIND_FRAMEWORK=last
  -DCMAKE_STRIP=/nix/store/nyhj00w339gk2gaj3faz70gjrnbmam8v-binutils-2.31.1/bin/strip
  -DCMAKE_RANLIB=/nix/store/nyhj00w339gk2gaj3faz70gjrnbmam8v-binutils-2.31.1/bin/ranlib
  -DCMAKE_AR=/nix/store/nyhj00w339gk2gaj3faz70gjrnbmam8v-binutils-2.31.1/bin/ar
  -DCMAKE_C_COMPILER=gcc
  -DCMAKE_CXX_COMPILER=g++
  -DCMAKE_INSTALL_PREFIX=/nix/store/10xp2rc351ymxly48isbn1vv5ihhikx3-gdtoa-desktop-unstable-2020-05-01
  -DRENAME_FUNCTIONS=ON
```

Which gives the following `/nix/store/10xp2rc351ymxly48isbn1vv5ihhikx3-gdtoa-desktop-unstable-2020-05-01/lib/pkgconfig/gdtoa-desktop.pc`:
```pkg-config
prefix=/nix/store/10xp2rc351ymxly48isbn1vv5ihhikx3-gdtoa-desktop-unstable-2020-05-01
libdir=/nix/store/10xp2rc351ymxly48isbn1vv5ihhikx3-gdtoa-desktop-unstable-2020-05-01/lib
includedir=/nix/store/10xp2rc351ymxly48isbn1vv5ihhikx3-gdtoa-desktop-unstable-2020-05-01/include

Name: gdtoa-desktop
Description: Binary↔decimal floating-point conversion library
Version: 0.1.20180730

Libs: -L${libdir} -lgdtoa-desktop
Cflags: -I${includedir}/gdtoa-desktop
```

I believe your issue lies somewhere in gdtoa-desktop's CMake `.pc` generation.

**Comment by 10110111** [comment]
```
$ ~/opt/cmake/bin/cmake .. -DCMAKE_INSTALL_PREFIX=$HOME/opt/gdtoa-desktop -DCMAKE_C_COMPILER=gcc-5
-- The C compiler identification is GNU 5.5.0
-- Check for working C compiler: /usr/bin/gcc-5
-- Check for working C compiler: /usr/bin/gcc-5 - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
++ Assuming the CPU does support SSE2, setting compiler flags to use it instead of x87
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ruslan/gdtoa-desktop/build
```
Resulting `gdtoa-desktop.pc`:
```
prefix=/home/ruslan/opt/gdtoa-desktop
libdir=/home/ruslan/opt/gdtoa-desktop/lib
includedir=/home/ruslan/opt/gdtoa-desktop/include

Name: gdtoa-desktop
Description: Binary↔decimal floating-point conversion library
Version: 0.1.20180730

Libs: -L${libdir} -lgdtoa-desktop
Cflags: -I${includedir}/gdtoa-desktop
```

**Comment by bb010g** [comment]
What's `tree ~/opt/gdtoa-desktop` give?

**Comment by 10110111** [comment]
```
/home/ruslan/opt/gdtoa-desktop/
├── include
│   └── gdtoa-desktop
│       ├── arith.h
│       └── gdtoa-desktop.h
└── lib
    ├── libgdtoa-desktop.so
    └── pkgconfig
        └── gdtoa-desktop.pc

4 directories, 4 files
```

**Comment by eteran** [comment]
Has there been any updates on this PR?

**Comment by eteran** [comment]
@bb010g I'm going to close this PR because there haven't been any updates on it recently. Please re-open if you are still looking to merge it at some point.

**Pull request closed without merging**
