### PR TITLE
Run lupdate on plugins too

### PR DESCRIPTION
**Pull request by 10110111**
This makes plugins translatable. The full command is:
```
lupdate src plugins -ts ./src/res/translations/edb_zh_CN.ts
```

### CODE REVIEW

**Comment by eteran** [comment]
This definitely will work correctly for first party plugins. One thing we will probably need to consider is how 3rd party plugins interact with translations (if at all). Do we eventually allow translation files to be embedded in the plugin themselves so they can be loaded as well?

**Comment by 10110111** [comment]
> Do we eventually allow translation files to be embedded in the plugin themselves so they can be loaded as well?

One way may be to query all the plugins for their own `QTranslator`s and install them after (or before?) the app's ones. Not sure how this would work for conflicting strings translated differently.

**Comment by eteran** [comment]
Yeah, something like this a good idea. We'll have to experiment with it.

**Comment by eteran** [comment]
@10110111 are you thinking that this one should be merged too?

**Comment by 10110111** [comment]
I think it's a good start to get something at least all the stock GUI translatable. If you come up with a way to make external plugins translatable, this can be done in subsequent commits, with the strings being already present (assuming you get your translators to fill them in), just waiting for possible splitting.

**Comment by eteran** [comment]
cool, i'll merge this in then :-)

Thanks as always!

**Pull request merged**
