### PR TITLE
Add completer for Go-To dialog

### PR DESCRIPTION
**Pull request by knikolenko**

### CODE REVIEW

**Comment by eteran** [comment]
Awesome, thanks!

**Comment by 10110111** [comment]
Won't this be awfully slow for large programs with lots of symbols? E.g. Symbols dialog already is quite slow in such cases.

**Comment by eteran** [comment]
Possibly. I can say that edb debugging itself is not too slow. edb isn't huge, but it isn't tiny either.

If it does turn out to be slow in some cases, I would consider that an issue worth filing in the tracker and exploring ways to make things faster.

**Comment by knikolenko** [comment]
Can create a QList of symbols in real time in the SymbolManager, instead of creating a list each time you call the GoTo dialog?

**Pull request merged**
