### PR TITLE
Program arguments in Recent Files and "Cold Restart" for debuggee

### PR DESCRIPTION
**Pull request by 10110111**
This set of commits
* implements saving debuggee arguments to recent programs list,
* makes it possible to use Restart action to start the most recently debugged program,
* adds some shortcuts to `DialogOpenProgram` and a better default directory.

### CODE REVIEW

**Comment by eteran** [comment]
Did you mean to alter the QHexview submodule version in b395630 ? Just making sure.

**Comment by eteran** [comment]
Just a self reminder, this resolves #267 once accepted :+1:

**Comment by 10110111** [comment]
Hmm, no, I didn't. Seems rebase went wrong. Will fix ASAP.

**Comment by 10110111** [comment]
OK, should be fixed now. Did a force push with correctly re-applied patches.

**Pull request merged**
